--- # written by user santosh kumar
- hosts: all
  user: santu
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_versions: 0.1lb
  vars_files:
     - conf/copyright.yml
     - conf/webdefalults.yml
  tasks:
     - name: Install apache web server
       action: yum name=httpd state=installed
       async: 300
       poll: 3
       notify: restart HTTPD
       #check_mode: no
     - name: verify the lynx web browser
       action: yum name=lynx state=present
  handlers:
     - name: restart HTTPD
       action: service name=httpd state=restarted
  


