--- #Tag functionality example
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  connection: ssh
  tasks:
    - name: Install the telnet and lynx package
      yum: pkg={{ item }} state=latest
      with_items:
         - telnet
         - lynx
      tags:
         - packages
         - name: verify that telent was installed
           raw: yum list installedd | grep telnet > /home/santu/pkg.log
           tags:
              - verifications
